### ISSUE TITLE
Provide a `get-pip.py`-like script for virtualenv

### ISSUE THREAD

**Issue by asottile** [pypa/get-virtualenv#1]
I often find myself on a machine with near-zero permissions (or a chroot / docker container) and have used this script: https://github.com/asottile/asottile.github.io#bootstrap-a-virtualenv-from-nothing

Would love to get this or something like this hosted similar to `get-pip.py`

**Comment by gaborbernat** [comment]
Somehow you need to get the bootstrapper on the machine though, not?

**Comment by asottile** [comment]
yes, that's what I'm proposing :)

**Comment by asottile** [comment]
oh perfect, that makes this even easier I think

**Comment by ncoghlan** [comment]
Yeah, I think Py2.4 was still in broad use back when get-pip.py was designed, so you have nicer options available to you now :)

**Comment by asottile** [comment]
got it working, would like some feedback before I write up news entries / decide further on the approach: https://github.com/pypa/virtualenv/pull/1287

**Comment by asottile** [comment]
I want to pick this up again and make it happen -- what needs doing here 😁

**Comment by gaborbernat** [comment]
We need something like https://github.com/pypa/get-pip; I don't think the **like** part is documented anywhere other than reading the code there and figuring out. We should probably try to generalize it to a library so any other project can use it 🤔

**Comment by asottile** [comment]
I think for virtualenv we don't need any of the complexity of `get-pip` -- [`make_zipapp.py`](https://github.com/pypa/virtualenv/blob/master/tasks/make_zipapp.py) builds `virtualenv.pyz` for us which I think (?) is all that's necessary

**Comment by pfmoore** [comment]
I guess there are 2 different possibilities:

1. You want a "single file executable" version of virtualenv, that you can just run with any Python interpreter that you have to hand, without "installing" it in any way. `virtualenv.py` is *almost* that, but it needs the `virtualenv_support` directory to bootstrap pip, setuptools and wheel. Bundling `virtualenv.py` and the support directory in a zipapp does the job here, though.
2. You want an installer for virtualenv, that can be used without having pip installed. That's basically what get-pip.py is, but the need for this is more important for pip, where it's a bootstrapping issue.

I assume what's wanted here is (1), and a pyz is a fine solution for that. Most of the complexities of `get-pip.py` are to solve bootstrapping issues that no-one but pip has.

**Comment by asottile** [comment]
yeah, I already did the work to make the zipapp for this purpose (1) -- I believe all that's needed is a place to stick it and docs that point at it (and a procedure to update it)

**Comment by pradyunsg** [comment]
@asottile We're on the issue tracker of exactly that repository :P

**Comment by pradyunsg** [comment]
Oh, nvm me. I need sleep. 😴

**Comment by anthrotype** [comment]
> I was hoping it could end up on https://bootstrap.pypa.io/get-virtualenv.py (similar to https://bootstrap.pypa.io/get-pip.py)

I was hoping too :+1: 
Is this still planned?

**Comment by anthrotype** [comment]
> I was hoping it could end up on https://bootstrap.pypa.io/get-virtualenv.py (similar to https://bootstrap.pypa.io/get-pip.py)

I was hoping too :+1: 
Is this still planned?

**Comment by gaborbernat** [comment]
I believe so 🤔 though maybe a zipapp is enough here, what's your use case?

**Comment by asottile** [comment]
yeah the zipapp should be enough, just need to get it hosted

**Comment by gaborbernat** [comment]
So I'll try to set this up with ``virtualenv-20.0.0b2.pyz``.

**Comment by gaborbernat** [comment]
So here's the proposal. Once this ticket is delivered we'll enable the following functionality:

```console
# download a self-packaged virtualenv
curl http://bootstrap.pypa.io/get-virtualenv.pyz
# point a python to it, and you're ready to create virtual environments
python get-virtualenv.pyz --help
```

Proposed behaviour:

- part of every virtualenv release will be to publish the generated zipapp to this repository (``~6MB file``). The latest zipapp will always live at the root of this repository.
- furthermore, we'll have the latest supported zipapp per python micro version via a directory structure; e.g: ``3.8/virtualenv.pyz`` will be a virtual zipapp that's supported under python3.8. Initially, these will just symlink to the root level (as initially, we support all those Pythons); however as we start dropping support for given versions these links might contain the last supported version.

```console
get-virtualenv/
├── virtualenv.pyz
├── 2.7
│   └── virtualenv.pyz
├── 3.4
│   └── virtualenv.pyz
├── 3.5
│   └── virtualenv.pyz
├── 3.6
│   └── virtualenv.pyz
├── 3.7
│   └── virtualenv.pyz
├── 3.8
│   └── virtualenv.pyz
└── 3.9
    └── virtualenv.pyz
```

- ``http://bootstrap.pypa.io/get-virtualenv.pyz`` will point to the ``virtualenv.pyz`` at the root level,
- ``http://bootstrap.pypa.io/3.8/virtualenv.pyz`` will point to the ``3.8/virtualenv.pyz`` file within the repository.

@ewdurbin can help set up this link from ``http://bootstrap.pypa.io`` to this repositories contents. Is everyone happy with this suggestion?

**Comment by asottile** [comment]
sounds good, looks a lot like how `get-pip` is set up

**Comment by ewdurbin** [comment]
Currently this will end up being a bit of a headache to maintain.

bootstrap.pypa.io currently pulls in three repositories

- https://github.com/pypa/get-pip/tree/master => `/srv/bootstrap/pip`
- https://github.com/pypa/setuptools/tree/bootstrap => `/srv/bootstrap/setuptools`
- https://github.com/buildout/buildout/tree/bootstrap-release => `/srv/bootstrap/buildout`

 and merges them via symlinks:

```
ernestd@web0:/srv/bootstrap/www$ tree -l
.
├── 2.6
│   └── get-pip.py -> /srv/bootstrap/pip/2.6/get-pip.py
├── 3.2
│   └── get-pip.py -> /srv/bootstrap/pip/3.2/get-pip.py
├── 3.3
│   └── get-pip.py -> /srv/bootstrap/pip/3.3/get-pip.py
├── 3.4
│   └── get-pip.py -> /srv/bootstrap/pip/3.4/get-pip.py
├── bootstrap-buildout.py -> /srv/bootstrap/buildout/bootstrap/bootstrap.py
├── ez_setup.py -> /srv/bootstrap/setuptools/ez_setup.py
└── get-pip.py -> /srv/bootstrap/pip/get-pip.py

4 directories, 7 files
```

You can see the way it is currently configured/managed [here](https://github.com/python/psf-salt/blob/master/salt/pypa/bootstrap/init.sls).

Adding virtualenv to the mix in this way will require all kinds of additional symlinks and purges and kind of makes me think it's time to rethink the way that bootstrap.pypa.io is constructed a bit.

It seems setuptools and buildout just have a single file, so I guess they can remain the same at the moment, but for get-pip and get-virtualenv I think it would make sense for us to restructure a bit by adding a `publish` directory to the top level of each repository that includes files that it would like to serve.

For get-pip that directory would basically be

```
publish/
├── 2.6
│   └── get-pip.py
├── 3.2
│   └── get-pip.py
├── 3.3
│   └── get-pip.py
├── 3.4
│   └── get-pip.py
└── get-pip.py
```

and for get-virtualenv, based on @gaborbernat's sketch above:

```
publish/
├── virtualenv.pyz
├── 2.7
│   └── virtualenv.pyz
├── 3.4
│   └── virtualenv.pyz
├── 3.5
│   └── virtualenv.pyz
├── 3.6
│   └── virtualenv.pyz
├── 3.7
│   └── virtualenv.pyz
├── 3.8
│   └── virtualenv.pyz
└── 3.9
    └── virtualenv.pyz
```

Then, give each a link with their name in the top level of bootstrap.pypa.io:

```
.
├── pip -> /srv/bootstrap/pip/publish
│   ├── 2.6
│   │   └── get-pip.py
│   ├── 3.2
│   │   └── get-pip.py
│   ├── 3.3
│   │   └── get-pip.py
│   ├── 3.4
│   │   └── get-pip.py
│   └── get-pip.py
└── virtualenv -> /srv/bootstrap/virtualenv/publish
    ├── 2.7
    │   └── virtualenv.pyz
    ├── 3.4
    │   └── virtualenv.pyz
    ├── 3.5
    │   └── virtualenv.pyz
    ├── 3.6
    │   └── virtualenv.pyz
    ├── 3.7
    │   └── virtualenv.pyz
    ├── 3.8
    │   └── virtualenv.pyz
    ├── 3.9
    │   └── virtualenv.pyz
    └── virtualenv.pyz
```

In an ideal world, that'd be that! If you want to boostrap pip, `curl https://boostrap.pypa.io/pip/get-pip.py`

But for backwards compatibility, we'd need to reconstruct the existing links. Some automation could scan the publish directories to create the top level version directories of existing projects, but if we want to make adding additional projects to boostrap.pypa.io a thing, it might make sense to move away from everything sharing the top level.

Would urls like `https://bootstrap.pypa.io/virtualenv/virtualenv.pyz` or `https://boostrap.pypa.io/virtualenv/3.8/virtualenv.pyz` be a problem?

**Comment by ewdurbin** [comment]
Alternatively, I suppose we could leave the "latest and greatest" in the top level `https://bootstrap.pypa.io/virtualenv.pyz` and for accessing specific versions `https://boostrap.pypa.io/virtualenv/3.8/virtualenv.pyz`

**Comment by ewdurbin** [comment]
@dstufft @pradyunsg @pfmoore it looks like y'all have been active in preparing/releasing things to bootstrap.pypa.io for get-pip and setuptools, thoughts on this?

**Comment by gaborbernat** [comment]
I'm personally happy with both proposals. What I'd like to achieve here is to have a link at root level-ish, that points to the latest. Then have one more in a subdirectory (path in case of URL), that would link to the latest that supports that ``major.minor`` combo.  Other than that whatever @dstufft, @pradyunsg or @pfmoore is fine by me 👍

**Comment by pradyunsg** [comment]
Ah, I thought I'd already responded (twice!)

Overall, I like the idea of making a directory in the repository be the public-facing directory, instead of depending on finer details of the repository's layout. The main change I suggest is that we call the directory `public` and not `publish` (mostly because that's common on web-stuff I've worked on, and the icon theme on my editor has a nice icon for that).

---

I think we should probably discuss the get-pip specific things (like maintaining existing routes) on the get-pip issue tracker: I've filed pypa/get-pip#61 for that.

**Comment by pradyunsg** [comment]
Noting that we'd probably want to add digests and/or signatures for the files as well. This reorganization has the benefit of making that easier to deploy/work on. (see https://github.com/pypa/get-pip/issues/47 and https://github.com/pypa/get-pip/issues/41)

**Comment by gaborbernat** [comment]
I've added to this repository the files as suggested, https://github.com/pypa/get-virtualenv/tree/master, version ``20.0.0b2``, see #2.

**Comment by ewdurbin** [comment]
@gaborbernat assuming that some tooling will eventually be added to the repository, I think the structure needs to be changed a bit to have a `public` directory (as @pradyunsg has recommended for the name). That directory should have what we actually want to serve on bootstrap.pypa.io.

**Comment by gaborbernat** [comment]
@ewdurbin just to confirm, should we move everything as it is within a public folder at the root of the repository? 👍

**Comment by ewdurbin** [comment]
I believe so, with the exception of the README

**Comment by gaborbernat** [comment]
Done via https://github.com/pypa/get-virtualenv/pull/3

**Comment by ewdurbin** [comment]
OK, this is being served on bootstrap.pypa.io as of https://github.com/python/psf-salt/commit/ab57d3e8d12d75585e42d1977dd7088f264f4944

@gaborbernat it looks like the symlinks in git weren't correct though, I resolved that in #4

**Comment by gaborbernat** [comment]
This is now live, thanks for all help, especially @ewdurbin !

- https://bootstrap.pypa.io/virtualenv.pyz
- https://bootstrap.pypa.io/3.8/virtualenv.pyz

**Comment by xavfernandez** [comment]
Nice :+1:
The version specific link seems to be https://bootstrap.pypa.io/virtualenv/3.8/virtualenv.pyz
