### ISSUE TITLE
How to find out what's the latest virtualenv.pyz version published

### ISSUE THREAD

**Issue by pombredanne** [pypa/get-virtualenv#37]
This would help know which version is effectively there and still allow getting the latest. That's a common pattern for shared objects on Linux and frameworks on macOS.

**Comment by gaborbernat** [comment]
You can load older versions from Github directly. For example:

```
https://github.com/pypa/get-virtualenv/raw/20.3.1/public/virtualenv.pyz
```

**Comment by pombredanne** [comment]
@gaborbernat 

> You can load older versions from Github directly. For example:
> 
> ```
> https://github.com/pypa/get-virtualenv/raw/20.3.1/public/virtualenv.pyz
> ```

I get that and I am using it. But my point is that there is no way to known easily what is the version of the current https://bootstrap.pypa.io/virtualenv/ short of actually downloading and introspecting the available virtualenv because there is no naming convention nor metadata standard for a pyz. The issue I have is having a bunch of virtualenv.pyz files laying around and no easy way of knowing which one is up to date, current and which one is out of date and old. Ideally I should be able to get that information from https://bootstrap.pypa.io/virtualenv/ somehow but today the only thing I have is  `virtualenv.pyz`

**Comment by gaborbernat** [comment]
That's a totally different question then. If you want to find out what's the latest version of virtualenv (which should match virtulenv.pyz, you/we can do a few things):

1. we can provide a ``https://bootstrap.pypa.io/virtualenv/version.txt`` containing the latest version number,
2. you can use https://warehouse.pypa.io/api-reference/json.html#project to find out what's the latest PyPi publish, the pyz should be the same,
3. you can use github API to get tags - https://api.github.com/repos/pypa/get-virtualenv/tags, the 0th element in the JSON is the latest,
4. download and introspect the metadata as you proposed.

My question to you then is that will 2/3 suffice, or you'd like 1?

**Comment by pombredanne** [comment]
@gaborbernat 

> we can provide a https://bootstrap.pypa.io/virtualenv/version.txt containing the latest version number,

this is the option I like most of your proposed ones. I would have added having a symlink on the web site that has a filename that contains the version as a another option e.g. adding either `virtualenv.pyz` being a link linking to `virtualenv-20.4.0.pyz` or  `virtualenv-20.4.0.pyz` being a link linking to `virtualenv.pyz`

**Comment by gaborbernat** [comment]
The issue I found with your proposal is that you still have to scan the website index to find the latest version. So how would you know to look for ``virtualenv-20.4.0.pyz`` and not ``virtualenv-20.4.1.pyz`` in case we symlink ``virtualenv.pyz``?

**Comment by pombredanne** [comment]
> The issue I found with your proposal is that you still have to scan the website index to find the latest version. So how would you know to look for `virtualenv-20.4.0.pyz` and not `virtualenv-20.4.1.pyz` in case we symlink `virtualenv.pyz`?

Good point! a version.txt would be better indeed then!

**Comment by gaborbernat** [comment]
https://github.com/pypa/get-virtualenv/commit/f94ea5958cd3c6f9faaeb248fcacab0b4b8aa39c adds it, I think the public HTML will sync soon too.
