### ISSUE TITLE
Question: are there too many bundled seed wheels? 

### ISSUE THREAD

**Issue by pombredanne** [pypa/get-virtualenv#38]
The latest virtualenv.pyz has been gaining some weight due mostly to more versions of seed wheels being bundled:
```
1360957 Jan 19 08:32 pip-19.1.1-py2.py3-none-any.whl
1518513 Jan 19 08:32 pip-20.3.1-py2.py3-none-any.whl
1520905 Jan 19 08:32 pip-20.3.3-py2.py3-none-any.whl
 583228 Jan 19 08:32 setuptools-43.0.0-py2.py3-none-any.whl
 583493 Jan 19 08:32 setuptools-44.1.1-py2.py3-none-any.whl
 785194 Jan 19 08:32 setuptools-50.3.2-py3-none-any.whl
 785164 Jan 19 08:32 setuptools-51.0.0-py3-none-any.whl
 786243 Jan 19 08:32 setuptools-51.3.3-py3-none-any.whl
  21556 Jan 19 08:32 wheel-0.33.6-py2.py3-none-any.whl
  34788 Jan 19 08:32 wheel-0.36.1-py2.py3-none-any.whl
  35046 Jan 19 08:32 wheel-0.36.2-py2.py3-none-any.whl
```
I wonder if keeping only the latest version would be enough? Folks that want to use older `virtualenv.pyz` could always get it from Git?

The size of the pyz would go roughly from 9.7MB to 4.5MB by doing so.

**Comment by gaborbernat** [comment]
Hi, the number of wheels we must include is determined by the python versions we support and what wheels of pip/setuptools/wheels that support. See https://github.com/pypa/virtualenv/blob/main/src/virtualenv/seed/wheels/embed/__init__.py#L7-L47. 

That being said the fact that ``setuptools-51.3.3-py3-none-any.whl`` and ``setuptools-51.0.0-py3-none-any.whl`` sounds to me like a bug in our virtualenv.pyz builder - https://github.com/pypa/virtualenv/blob/main/tasks/make_zipapp.py.

**Comment by gaborbernat** [comment]
Ran into this again, seems the issue is that our builder does not clean the folder before starting, so if has wheels for older versions of virtualenv those will be packed again.

**Comment by pombredanne** [comment]
There is likely some remaining issue with the latest https://github.com/pypa/get-virtualenv/blob/20.16.3/public/virtualenv.pyz

There is a pip wheel version in /virtualenv/seed/wheels/embed/pip-22.2.1-py3-none-any.whl that's does not seemused anywhere and makes double duty with pip-22.2.2-py3-none-any.whl IMHO. That's an extra 2MB. 

And since Python 2.7, 3.4 and 3.5 have been dropped from the latest... there is IMHO another opportunity to further trim embeds to only the current version of pip/setuptools/wheels used for Python 3.6+

Doing so could shrink the pyz size from ~13.5MB to ~5.4MB

**Comment by gaborbernat** [comment]
> And since Python 2.7, 3.4 and 3.5 have been dropped from the latest... there is IMHO another opportunity to further trim embeds to only the current version of pip/setuptools/wheels used for Python 3.6+\n\nDoing so could shrink the pyz size from ~13.5MB to ~5.4MB

You're mistaken here. While we did drop runtime support for those Python interpreters we did not drop target support. So we still need all those extra packages. At some point we'll drop target support at which point we'll make those extra optimizations.

**Comment by pombredanne** [comment]
> You're mistaken here.

Fai enough... but what about this?

> There is a pip wheel version in /virtualenv/seed/wheels/embed/pip-22.2.1-py3-none-any.whl that's does not seem used anywhere and makes double duty with pip-22.2.2-py3-none-any.whl IMHO. That's an extra 2MB.

**Comment by gaborbernat** [comment]
Yeah  pip-22.2.2-py3-none-any.whl is an actual issue.
