### ISSUE TITLE
Rename the default branch from `master` to `main`

### ISSUE THREAD

**Issue by DiddiLeija** [pypa/get-virtualenv#42]
Hi everybody! I have seen that many PyPA repositories are changing its default branch name to `main`. Can we do the same on this repo?

**Comment by gaborbernat** [comment]
That would be up to @ewdurbin to ensure upstream pulls its content from that branch.

**Comment by ewdurbin** [comment]
Automation pulls from the default branch, so changing that here is sufficient.

**Comment by ewdurbin** [comment]
went ahead and renamed it using GitHub's tools.
