### ISSUE TITLE
Consider removing GitHub releases

### ISSUE THREAD

**Issue by pombredanne** [pypa/get-virtualenv#43]
There are a bunch of old releases in https://github.com/pypa/get-virtualenv/releases
They serve no real purpose and do not add much value over tags... yet since only older releases are there it hides the newer tags on the project homepage which is somewhat misleading as it would let visitors believe that the last release was in July 2021.
I suggest removing/deleting these 24 releases: their tags will become visible on the main page.

**Comment by gaborbernat** [comment]
Done.
